### ISSUE TITLE
Crashes after x2 requests

### ISSUE THREAD

**Issue by Tybost** [1nnovat1on/gpt_chatbot#2]
Thanks for making this =) but unfortunately, it hangs after two requests and requires to be restarted to use it again. This is my first post on github and I'm pretty nooby at all of this; so I'm not entirely sure what to provide here since there are no error messages. 

My system: i7 8700k, 2080, 32GB
**Here's a quick video going through the startup process/hangup crash:**  https://streamable.com/fsykcc

... While I'm at it
**[Feature Request]**: I would like to be able to reroute the ElevenLabs speaking audio into other cables such as (VB-Audio Cable) instead of having the audio read thru desktop audio. ie. Select Microphone + Select Speakers much like how the SpeechToSpeech plugin handles it: **Speech To Speech using ElevenLabs:** https://github.com/lugia19/speechToSpeechElevenLabs
Why? - It would be cool to be able to use this as an easy gateway to creating a "Virtual Content Creator" like Neuro-Sama that responds to questions. https://youtu.be/jAWS3K_3jqQ?t=58

**Comment by 1nnovat1on** [comment]
Thank you very much for this work!

I’ll take a look at why it’s crashing. Give me a few days.

**Comment by 1nnovat1on** [comment]
> Thanks for making this =) but unfortunately, it hangs after two requests and requires to be restarted to use it again. This is my first post on github and I'm pretty nooby at all of this; so I'm not entirely sure what to provide here since there are no error messages.
> 
> My system: i7 8700k, 2080, 32GB **Here's a quick video going through the startup process/hangup crash:** https://streamable.com/fsykcc
> 
> ... While I'm at it **[Feature Request]**: I would like to be able to reroute the ElevenLabs speaking audio into other cables such as (VB-Audio Cable) instead of having the audio read thru desktop audio. ie. Select Microphone + Select Speakers much like how the SpeechToSpeech plugin handles it: **Speech To Speech using ElevenLabs:** https://github.com/lugia19/speechToSpeechElevenLabs Why? - It would be cool to be able to use this as an easy gateway to creating a "Virtual Content Creator" like Neuro-Sama that responds to questions. https://youtu.be/jAWS3K_3jqQ?t=58

Okay so long shot here, have you tried just continuing to talk? It listens and replies without you needing to click again. Once you 'wake' it up, you can talk back and forth with the bot. It freezes while it's active, which I am looking into now.

Does changing the output on your machine allow you to do what you need?

**Comment by Tybost** [comment]
So after trying again with greater patience - I got 10 responses without crashing but the response times were beyond expectations. I had assumed it was failing before and clicked the windows moving them around which led to a hangup and eventual crash.

Changing the audio output (via windows) is unreliable / it isn't detected as an app.

Eleven Labs API is pretty slow. Sometimes it takes 30 seconds to request and other times a minute.

**Comment by 1nnovat1on** [comment]
I see... I'm going to look into a way to change the audio output like in your example... give me some time.

As for API times, I unfortunately don't know how to speed that up currently. I think I will need to stream the audio rather than save to disk.
